---
- name: sonarqube | create plugin directory
  file: path="{{ sonar.dir }}/plugins" state=directory

- name: sonarqube | copy plugins files
  copy:
    src: "{{ item }}"
    dest: "{{ sonar.dir }}/plugins/"
  with_items:
    - sonar-auth-oidc-plugin-2.0.0.jar
    - sonarqube-community-branch-plugin-1.3.2-SNAPSHOT.jar
